# Generated by Django 5.1.2 on 2024-10-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_rename_product_order_name_remove_order_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GTX1080ti', 'GTX1080ti'), ('GTX2080ti', 'GTX2080ti'), ('GTX3080ti', 'GTX3080ti'), ('GTX3090ti', 'GTX3090ti'), ('GTX4090ti', 'GTX4090ti')], max_length=50, null=True),
        ),
    ]
